name: drinks
description: "Drinks informations."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.2
  provider: ^6.1.2
  html: ^0.15.5
  photo_view: ^0.15.0
  cached_network_image: ^3.4.0
  connectivity: ^3.0.6
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true  
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
  web:
    generate: false    
  windows:
    generate: false    
  macos:
    generate: false    